name: Build and Deploy - Azure
on:
  workflow_dispatch:

jobs:
  build-dotnet:
    name: Build .NET
    runs-on: ubuntu-latest
    env:
      PROJECT: WarcraftGearPlanner.Server/WarcraftGearPlanner.Server.csproj
      BUILD-CONFIG: Release

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x"
          include-prerelease: true

      - name: .NET Build
        run: dotnet build {{env.PROJECT}} -c {{env.BUILD-CONFIG}}

      - name: .NET Publish
        run: dotnet publish {{env.PROJECT}} -c {{env.BUILD-CONFIG}} -o ${{env.DOTNET_ROOT}}/warcraft-gear-planner

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/warcraft-gear-planner

  deploy-azure:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build-dotnet
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "warcraft-gear-planner"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4B16975D67814F11A7BB7201E645C8D2 }}
          package: .
