name: Build and Deploy - API Docker Image
on:
  workflow_dispatch:
  pull_request:
    branches: [ 'master' ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment:
      name: 'PROD - API'
      url: 'https://wgp-api.azurewebsites.net'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
  
      - name: Build the Docker Image
        run: docker build . --file WarcraftGearPlanner.Server/Dockerfile --tag warcraft-gear-planner:$(date +%s)
